In [21]:
import pandas as pd

In [22]:
dataset = pd.read_excel("/content/melb_data.xlsx")
dataset.head(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,2016-12-03,2.5,3067.0,...,1,1.0,202.0,NaN,NaN,Yarra,NaN,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,2016-02-04,2.5,3067.0,...,1,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,2017-03-04,2.5,3067.0,...,2,0.0,134.0,150.0,1900.0,NaN,-37.8093,NaN,Northern Metropolitan,4019.0

In [23]:
dataset.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode          138
hoal              118
Bathroom            0
Car               144
Landsize          121
BuildingArea     6450
YearBuilt        5375
CouncilArea      1487
Lattitude          36
Longtitude         71
Regionname         15
Propertycount      92
dtype: int64

In [50]:
dataset.columns = dataset.columns.str.strip().str.lower()
dataset["councilarea"] = dataset["councilarea"].fillna(dataset["councilarea"].mode()[0])

In [56]:
dataset.columns = dataset.columns.str.strip().str.lower()
dataset["propertycount"] = dataset["propertycount"].fillna(dataset["propertycount"].mode()[0])

In [58]:
en_data = dataset[["councilarea", "propertycount"]]
en_data

      councilarea  propertycount
0           Yarra         4019.0
1           Yarra         4019.0
2        Moreland         4019.0
3           Yarra         4019.0
4           Yarra         4019.0
...           ...            ...
13575    Moreland         7392.0
13576    Moreland         6380.0
13577    Moreland         6380.0
13578    Moreland         6380.0
13579    Moreland         6543.0

[13580 rows x 2 columns]

from matplotlib import pyplot as plt
en_data['propertycount'].plot(kind='hist', bins=20, title='propertycount')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
en_data['propertycount'].plot(kind='line', figsize=(8, 4), title='propertycount')
plt.gca().spines[['top', 'right']].set_visible(False)

In [59]:
pd.get_dummies(en_data)

,propertycount,councilarea_Banyule,councilarea_Bayside,councilarea_Boroondara,councilarea_Brimbank,councilarea_Cardinia,councilarea_Casey,councilarea_Darebin,councilarea_Frankston,councilarea_Glen Eira,...,councilarea_Moreland,councilarea_Nillumbik,councilarea_Port Phillip,councilarea_Stonnington,councilarea_Unavailable,councilarea_Whitehorse,councilarea_Whittlesea,councilarea_Wyndham,councilarea_Yarra,councilarea_Yarra Ranges
0,4019.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,4019.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,4019.0,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,4019.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,4019.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,7392.0,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
13576,6380.0,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
13577,6380.0,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
13578,6380.0,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
13579,6543.0,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

Warning: Total number of columns (34) exceeds max_columns (20) limiting to first (20) columns.

from matplotlib import pyplot as plt
_df_5['propertycount'].plot(kind='hist', bins=20, title='propertycount')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('councilarea_Banyule').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_7.groupby('councilarea_Bayside').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_8.groupby('councilarea_Boroondara').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_9.groupby('councilarea_Brimbank').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_10['propertycount'].plot(kind='line', figsize=(8, 4), title='propertycount')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['councilarea_Bayside'].value_counts()
    for x_label, grp in _df_11.groupby('councilarea_Banyule')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('councilarea_Banyule')
_ = plt.ylabel('councilarea_Bayside')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['councilarea_Boroondara'].value_counts()
    for x_label, grp in _df_12.groupby('councilarea_Bayside')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('councilarea_Bayside')
_ = plt.ylabel('councilarea_Boroondara')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['councilarea_Brimbank'].value_counts()
    for x_label, grp in _df_13.groupby('councilarea_Boroondara')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('councilarea_Boroondara')
_ = plt.ylabel('councilarea_Brimbank')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['councilarea_Cardinia'].value_counts()
    for x_label, grp in _df_14.groupby('councilarea_Brimbank')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('councilarea_Brimbank')
_ = plt.ylabel('councilarea_Cardinia')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['councilarea_Banyule'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='propertycount', y='councilarea_Banyule', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_16['councilarea_Bayside'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_16, x='propertycount', y='councilarea_Bayside', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['councilarea_Boroondara'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='propertycount', y='councilarea_Boroondara', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

In [65]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   propertycount                  13580 non-null  float64
 1   councilarea_Banyule            13580 non-null  bool
 2   councilarea_Bayside            13580 non-null  bool
 3   councilarea_Boroondara         13580 non-null  bool
 4   councilarea_Brimbank           13580 non-null  bool
 5   councilarea_Cardinia           13580 non-null  bool
 6   councilarea_Casey              13580 non-null  bool
 7   councilarea_Darebin            13580 non-null  bool
 8   councilarea_Frankston          13580 non-null  bool
 9   councilarea_Glen Eira          13580 non-null  bool
 10  councilarea_Greater Dandenong  13580 non-null  bool
 11  councilarea_Hobsons Bay        13580 non-null  bool
 12  councilarea_Hume               13580 non-null  bool
 13  councilarea_Kingston           13580 non-null  bool
 14  councilarea_Knox               13580 non-null  bool
 15  councilarea_Macedon Ranges     13580 non-null  bool
 16  councilarea_Manningham         13580 non-null  bool
 17  councilarea_Maribyrnong        13580 non-null  bool
 18  councilarea_Maroondah          13580 non-null  bool
 19  councilarea_Melbourne          13580 non-null  bool
 20  councilarea_Melton             13580 non-null  bool
 21  councilarea_Monash             13580 non-null  bool
 22  councilarea_Moonee Valley      13580 non-null  bool
 23  councilarea_Moorabool          13580 non-null  bool
 24  councilarea_Moreland           13580 non-null  bool
 25  councilarea_Nillumbik          13580 non-null  bool
 26  councilarea_Port Phillip       13580 non-null  bool
 27  councilarea_Stonnington        13580 non-null  bool
 28  councilarea_Unavailable        13580 non-null  bool
 29  councilarea_Whitehorse         13580 non-null  bool
 30  councilarea_Whittlesea         13580 non-null  bool
 31  councilarea_Wyndham            13580 non-null  bool
 32  councilarea_Yarra              13580 non-null  bool
 33  councilarea_Yarra Ranges       13580 non-null  bool
dtypes: bool(33), float64(1)
memory usage: 543.9 KB

In [60]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   propertycount                  13580 non-null  float64
 1   councilarea_Banyule            13580 non-null  bool
 2   councilarea_Bayside            13580 non-null  bool
 3   councilarea_Boroondara         13580 non-null  bool
 4   councilarea_Brimbank           13580 non-null  bool
 5   councilarea_Cardinia           13580 non-null  bool
 6   councilarea_Casey              13580 non-null  bool
 7   councilarea_Darebin            13580 non-null  bool
 8   councilarea_Frankston          13580 non-null  bool
 9   councilarea_Glen Eira          13580 non-null  bool
 10  councilarea_Greater Dandenong  13580 non-null  bool
 11  councilarea_Hobsons Bay        13580 non-null  bool
 12  councilarea_Hume               13580 non-null  bool
 13  councilarea_Kingston           13580 non-null  bool
 14  councilarea_Knox               13580 non-null  bool
 15  councilarea_Macedon Ranges     13580 non-null  bool
 16  councilarea_Manningham         13580 non-null  bool
 17  councilarea_Maribyrnong        13580 non-null  bool
 18  councilarea_Maroondah          13580 non-null  bool
 19  councilarea_Melbourne          13580 non-null  bool
 20  councilarea_Melton             13580 non-null  bool
 21  councilarea_Monash             13580 non-null  bool
 22  councilarea_Moonee Valley      13580 non-null  bool
 23  councilarea_Moorabool          13580 non-null  bool
 24  councilarea_Moreland           13580 non-null  bool
 25  councilarea_Nillumbik          13580 non-null  bool
 26  councilarea_Port Phillip       13580 non-null  bool
 27  councilarea_Stonnington        13580 non-null  bool
 28  councilarea_Unavailable        13580 non-null  bool
 29  councilarea_Whitehorse         13580 non-null  bool
 30  councilarea_Whittlesea         13580 non-null  bool
 31  councilarea_Wyndham            13580 non-null  bool
 32  councilarea_Yarra              13580 non-null  bool
 33  councilarea_Yarra Ranges       13580 non-null  bool
dtypes: bool(33), float64(1)
memory usage: 543.9 KB

In [61]:
from sklearn.preprocessing import OneHotEncoder

In [73]:
ohe = OneHotEncoder(drop="first")
ar = ohe.fit_transform(en_data).toarray()
ar

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [74]:
column_names = list(ohe.get_feature_names_out(["councilarea", "propertycount"]))
pd.DataFrame(ar, columns=column_names)

,councilarea_Bayside,councilarea_Boroondara,councilarea_Brimbank,councilarea_Cardinia,councilarea_Casey,councilarea_Darebin,councilarea_Frankston,councilarea_Glen Eira,councilarea_Greater Dandenong,councilarea_Hobsons Bay,...,propertycount_14949.0,propertycount_15321.0,propertycount_15510.0,propertycount_15542.0,propertycount_16166.0,propertycount_17055.0,propertycount_17093.0,propertycount_17384.0,propertycount_17496.0,propertycount_21650.0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13577,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13578,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13579,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0