In [95]:
import pandas as pd

In [97]:
df = pd.DataFrame({"Size":["m","l","xl","s","m","l","s","s","l","xl","m"]})
df.head()

  Size
0    m
1    l
2   xl
3    s
4    m

from matplotlib import pyplot as plt
import seaborn as sns
_df_115.groupby('Size').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_116['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_117.groupby('Size').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_118.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Size')):
  _plot_series(series, series_name, i)
  fig.legend(title='Size', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_119['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_120['Size'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_120, x='index', y='Size', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [98]:
ord_data = [["s","m","l","xl"]]

In [99]:
from sklearn.preprocessing import OrdinalEncoder

In [103]:
oe = OrdinalEncoder(categories=ord_data)
oe.fit(df[["Size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [105]:
df["Size_en"] = oe.transform(df[["Size"]])

In [106]:
df

   Size  Size_en
0     m      1.0
1     l      2.0
2    xl      3.0
3     s      0.0
4     m      1.0
5     l      2.0
6     s      0.0
7     s      0.0
8     l      2.0
9    xl      3.0
10    m      1.0

from matplotlib import pyplot as plt
_df_105['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_106['Size_en'].plot(kind='hist', bins=20, title='Size_en')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_107.groupby('Size').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_108.plot(kind='scatter', x='index', y='Size_en', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Size_en']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_109.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Size')):
  _plot_series(series, series_name, i)
  fig.legend(title='Size', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Size_en')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_110.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Size')):
  _plot_series(series, series_name, i)
  fig.legend(title='Size', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_111['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_112['Size_en'].plot(kind='line', figsize=(8, 4), title='Size_en')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_113['Size'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_113, x='index', y='Size', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_114['Size'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_114, x='Size_en', y='Size', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [112]:
ord_data1 = {"s":10,"m":11,"x":12,"xl":13}

In [113]:
df["Size_en_data"] = df["Size"].map(ord_data1)

In [114]:
df

   Size  Size_en  Size_en_data
0     m      1.0          11.0
1     l      2.0           NaN
2    xl      3.0          13.0
3     s      0.0          10.0
4     m      1.0          11.0
5     l      2.0           NaN
6     s      0.0          10.0
7     s      0.0          10.0
8     l      2.0           NaN
9    xl      3.0          13.0
10    m      1.0          11.0

from matplotlib import pyplot as plt
df['Size_en'].plot(kind='hist', bins=20, title='Size_en')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Size_en_data'].plot(kind='hist', bins=20, title='Size_en_data')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Size').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Size_en', y='Size_en_data', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Size_en'].plot(kind='line', figsize=(8, 4), title='Size_en')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['Size_en_data'].plot(kind='line', figsize=(8, 4), title='Size_en_data')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Size'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Size_en', y='Size', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Size'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Size_en_data', y='Size', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [115]:
dataset = pd.read_excel("/content/melb_data.xlsx")
dataset.head(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,2016-12-03,2.5,3067.0,...,1,1.0,202.0,NaN,NaN,Yarra,NaN,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,2016-02-04,2.5,3067.0,...,1,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,2017-03-04,2.5,3067.0,...,2,0.0,134.0,150.0,1900.0,NaN,-37.8093,NaN,Northern Metropolitan,4019.0

In [116]:
dataset["Regionname"].unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', nan, 'Eastern Metropolitan',
       'South-Eastern Metropolitan', 'Eastern Victoria',
       'Northern Victoria', 'Western Victoria'], dtype=object)

In [118]:
dataset["Regionname"] = dataset["Regionname"].fillna(dataset["Regionname"].mode()[0])

In [127]:
en_data_ord = [dataset["Regionname"].unique()]

In [120]:
from sklearn.preprocessing import OrdinalEncoder

In [129]:
oen = OrdinalEncoder(categories=en_data_ord)

In [131]:
dataset["Regionname"] =oen.fit_transform(dataset[["Regionname"]])